apiVersion: apps/v1
kind: Deployment
metadata:
  name: komodor-nginx-deployment
  labels:
    app.komodor.com/label.team: backend
    app.komodor.com/label.group: infrastructure
    app.komodor.com/label.owners: "infa-team"
    app.komodor.com/label.alert-team: "devs"
    app.komodor.com/label.Impacted-by: redis
  annotations:
spec:
  selector:
    matchLabels:
      app: komodor-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: komodor-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80