apiVersion: apps/v1
kind: Deployment
metadata:
  name: komodor-nginx-deployment
  annotations:
    app.komodor.com/service.link.grafana-overall-system-health: "https://grafana.com/service/annotation-example"
    app.komodor.com/service.link.datadog-APM: "https://datadog.com/dashboard/annotation-example"
    app.komodor.com/service.link.playbook: "https://docs.google.com/playbook"
    app.komodor.com/deploy.job.jenkins: "https://ci.jenkins-ci.org/computer/job"
    app.komodor.com/deploy.link.logs: "https://app.logz.io/#/dashboard/kibana/discover?_a=env:1.0.1"
    app.komodor.com/deploy.link.sentry: "https://sentry.io/organizations/rookoutz/issues/?project=1320440&query=sdk.version%3A1.0.1&statsPeriod=14d"
    app.komodor.com/service.link.datadog: "https://app.datadoghq.com/apm/traces?query=service%3A${service}%20kube_namespace%3A${namespace}%20env%3A${cluster}&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&streamTraces=true&start=${epochStart}&end=${epochEnd}&paused=true"
spec:
  selector:
    matchLabels:
      app: komodor-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: komodor-nginx
    spec:
      containers:
      - name: nginx-demo
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
      - name: nginx-demo1
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8
          initialDelaySeconds: 3
          periodSeconds: 3