apiVersion: apps/v1
kind: Deployment
metadata:
  name: komodor-nginx-deployment
  annotations:
    app.komodor.com/service.link.grafana-overall-system-health: "https://grafana.com/service/annotation-example"
    app.komodor.com/service.link.datadog: "https://datadog.com/dashboard/annotation-example"
    app.komodor.com/service.link.playbook: "https://docs.google.com/playbook"
spec:
  selector:
    matchLabels:
      app: komodor-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: komodor-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80